{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.aheaditec.widgetizing.ExtIdentityProvider\/documentation\/ExtIdentityProviderFramework"},"metadata":{"role":"collection","modules":[{"name":"ExtIdentityProviderFramework"}],"title":"ExtIdentityProviderFramework","symbolKind":"module","externalID":"ExtIdentityProviderFramework","roleHeading":"Framework"},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[[]]},"sections":[],"variants":[{"paths":["\/documentation\/extidentityproviderframework"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/extidentityproviderframework"]}],"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/com.aheaditec.widgetizing.ExtIdentityProvider\/documentation\/ExtIdentityProviderFramework\/ExtIdentityProvider","doc:\/\/com.aheaditec.widgetizing.ExtIdentityProvider\/documentation\/ExtIdentityProviderFramework\/ExtIdentityProviderVerification","doc:\/\/com.aheaditec.widgetizing.ExtIdentityProvider\/documentation\/ExtIdentityProviderFramework\/InitResponseDataObject"],"title":"Classes"},{"identifiers":["doc:\/\/com.aheaditec.widgetizing.ExtIdentityProvider\/documentation\/ExtIdentityProviderFramework\/DictionaryWithDefault","doc:\/\/com.aheaditec.widgetizing.ExtIdentityProvider\/documentation\/ExtIdentityProviderFramework\/LogoImage","doc:\/\/com.aheaditec.widgetizing.ExtIdentityProvider\/documentation\/ExtIdentityProviderFramework\/Request","doc:\/\/com.aheaditec.widgetizing.ExtIdentityProvider\/documentation\/ExtIdentityProviderFramework\/WidgetState"],"title":"Structures"},{"identifiers":["doc:\/\/com.aheaditec.widgetizing.ExtIdentityProvider\/documentation\/ExtIdentityProviderFramework\/ExtIdentityProviderWidgetError"],"title":"Enumerations"}],"references":{"doc://com.aheaditec.widgetizing.ExtIdentityProvider/documentation/ExtIdentityProviderFramework/ExtIdentityProviderVerification":{"identifier":"doc:\/\/com.aheaditec.widgetizing.ExtIdentityProvider\/documentation\/ExtIdentityProviderFramework\/ExtIdentityProviderVerification","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ExtIdentityProviderVerification"}],"navigatorTitle":[{"text":"ExtIdentityProviderVerification","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","title":"ExtIdentityProviderVerification","url":"\/documentation\/extidentityproviderframework\/extidentityproviderverification"},"doc://com.aheaditec.widgetizing.ExtIdentityProvider/documentation/ExtIdentityProviderFramework/ExtIdentityProviderWidgetError":{"role":"symbol","identifier":"doc:\/\/com.aheaditec.widgetizing.ExtIdentityProvider\/documentation\/ExtIdentityProviderFramework\/ExtIdentityProviderWidgetError","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ExtIdentityProviderWidgetError"}],"abstract":[],"type":"topic","title":"ExtIdentityProviderWidgetError","navigatorTitle":[{"kind":"identifier","text":"ExtIdentityProviderWidgetError"}],"url":"\/documentation\/extidentityproviderframework\/extidentityproviderwidgeterror","kind":"symbol"},"doc://com.aheaditec.widgetizing.ExtIdentityProvider/documentation/ExtIdentityProviderFramework/Request":{"abstract":[{"type":"text","text":"Represents an OpenID Connect (OIDC) request with an external Identity Provider (IdP) for the frontend."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Request"}],"identifier":"doc:\/\/com.aheaditec.widgetizing.ExtIdentityProvider\/documentation\/ExtIdentityProviderFramework\/Request","navigatorTitle":[{"kind":"identifier","text":"Request"}],"kind":"symbol","url":"\/documentation\/extidentityproviderframework\/request","role":"symbol","title":"Request","type":"topic"},"doc://com.aheaditec.widgetizing.ExtIdentityProvider/documentation/ExtIdentityProviderFramework/ExtIdentityProviderVersionString":{"title":"ExtIdentityProviderVersionString","abstract":[{"text":"Project version string for ExtIdentityProvider.","type":"text"}],"kind":"symbol","url":"\/documentation\/extidentityproviderframework\/extidentityproviderversionstring","role":"symbol","identifier":"doc:\/\/com.aheaditec.widgetizing.ExtIdentityProvider\/documentation\/ExtIdentityProviderFramework\/ExtIdentityProviderVersionString","type":"topic","fragments":[{"kind":"identifier","text":"ExtIdentityProviderVersionString"}]},"doc://com.aheaditec.widgetizing.ExtIdentityProvider/documentation/ExtIdentityProviderFramework/DictionaryWithDefault":{"navigatorTitle":[{"kind":"identifier","text":"DictionaryWithDefault"}],"url":"\/documentation\/extidentityproviderframework\/dictionarywithdefault","role":"symbol","title":"DictionaryWithDefault","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DictionaryWithDefault"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.aheaditec.widgetizing.ExtIdentityProvider\/documentation\/ExtIdentityProviderFramework\/DictionaryWithDefault"},"doc://com.aheaditec.widgetizing.ExtIdentityProvider/documentation/ExtIdentityProviderFramework":{"url":"\/documentation\/extidentityproviderframework","role":"collection","title":"ExtIdentityProviderFramework","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.aheaditec.widgetizing.ExtIdentityProvider\/documentation\/ExtIdentityProviderFramework"},"doc://com.aheaditec.widgetizing.ExtIdentityProvider/documentation/ExtIdentityProviderFramework/InitResponseDataObject":{"abstract":[{"type":"text","text":"List of OIDC requests provided for FE decision which IdP will be used"}],"navigatorTitle":[{"text":"InitResponseDataObject","kind":"identifier"}],"title":"InitResponseDataObject","identifier":"doc:\/\/com.aheaditec.widgetizing.ExtIdentityProvider\/documentation\/ExtIdentityProviderFramework\/InitResponseDataObject","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"InitResponseDataObject"}],"url":"\/documentation\/extidentityproviderframework\/initresponsedataobject"},"doc://com.aheaditec.widgetizing.ExtIdentityProvider/documentation/ExtIdentityProviderFramework/WidgetState":{"kind":"symbol","navigatorTitle":[{"text":"WidgetState","kind":"identifier"}],"abstract":[{"type":"text","text":"Represents the current state of the widget."}],"type":"topic","title":"WidgetState","url":"\/documentation\/extidentityproviderframework\/widgetstate","identifier":"doc:\/\/com.aheaditec.widgetizing.ExtIdentityProvider\/documentation\/ExtIdentityProviderFramework\/WidgetState","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WidgetState","kind":"identifier"}]},"doc://com.aheaditec.widgetizing.ExtIdentityProvider/documentation/ExtIdentityProviderFramework/ExtIdentityProvider":{"abstract":[{"text":"Initial class in ExtIdentityProvider widget call sequence","type":"text"}],"url":"\/documentation\/extidentityproviderframework\/extidentityprovider","role":"symbol","type":"topic","kind":"symbol","title":"ExtIdentityProvider","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ExtIdentityProvider","kind":"identifier"}],"identifier":"doc:\/\/com.aheaditec.widgetizing.ExtIdentityProvider\/documentation\/ExtIdentityProviderFramework\/ExtIdentityProvider","navigatorTitle":[{"kind":"identifier","text":"ExtIdentityProvider"}]},"doc://com.aheaditec.widgetizing.ExtIdentityProvider/documentation/ExtIdentityProviderFramework/LogoImage":{"abstract":[{"text":"Represents a logo image with its URL and dimensions.","type":"text"}],"title":"LogoImage","type":"topic","role":"symbol","identifier":"doc:\/\/com.aheaditec.widgetizing.ExtIdentityProvider\/documentation\/ExtIdentityProviderFramework\/LogoImage","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"LogoImage"}],"url":"\/documentation\/extidentityproviderframework\/logoimage","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"LogoImage","kind":"identifier"}]},"doc://com.aheaditec.widgetizing.ExtIdentityProvider/documentation/ExtIdentityProviderFramework/ExtIdentityProviderVersionNumber":{"type":"topic","abstract":[{"type":"text","text":"Project version number for ExtIdentityProvider."}],"role":"symbol","kind":"symbol","url":"\/documentation\/extidentityproviderframework\/extidentityproviderversionnumber","identifier":"doc:\/\/com.aheaditec.widgetizing.ExtIdentityProvider\/documentation\/ExtIdentityProviderFramework\/ExtIdentityProviderVersionNumber","title":"ExtIdentityProviderVersionNumber","fragments":[{"kind":"identifier","text":"ExtIdentityProviderVersionNumber"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.aheaditec.widgetizing.ExtIdentityProvider\/documentation\/ExtIdentityProviderFramework\/ExtIdentityProviderVersionNumber","doc:\/\/com.aheaditec.widgetizing.ExtIdentityProvider\/documentation\/ExtIdentityProviderFramework\/ExtIdentityProviderVersionString"],"title":"Variables"}],"op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"}],"traits":[{"interfaceLanguage":"occ"}]}]}