{"variants":[{"paths":["\/documentation\/passwordframework"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/passwordframework"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"modules":[{"name":"PasswordFramework"}],"role":"collection","title":"PasswordFramework","roleHeading":"Framework","externalID":"PasswordFramework","symbolKind":"module"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","identifier":{"url":"doc:\/\/com.aheaditec.widgetizing.Password\/documentation\/PasswordFramework","interfaceLanguage":"swift"},"topicSections":[{"title":"Classes","identifiers":["doc:\/\/com.aheaditec.widgetizing.Password\/documentation\/PasswordFramework\/Password","doc:\/\/com.aheaditec.widgetizing.Password\/documentation\/PasswordFramework\/PasswordVerification"]},{"title":"Structures","identifiers":["doc:\/\/com.aheaditec.widgetizing.Password\/documentation\/PasswordFramework\/InitResponseDataObject"]},{"title":"Enumerations","identifiers":["doc:\/\/com.aheaditec.widgetizing.Password\/documentation\/PasswordFramework\/PasswordWidgetError"]}],"hierarchy":{"paths":[[]]},"references":{"doc://com.aheaditec.widgetizing.Password/documentation/PasswordFramework/PasswordVersionNumber":{"kind":"symbol","identifier":"doc:\/\/com.aheaditec.widgetizing.Password\/documentation\/PasswordFramework\/PasswordVersionNumber","type":"topic","abstract":[{"type":"text","text":"Project version number for Password."}],"url":"\/documentation\/passwordframework\/passwordversionnumber","role":"symbol","title":"PasswordVersionNumber","fragments":[{"kind":"identifier","text":"PasswordVersionNumber"}]},"doc://com.aheaditec.widgetizing.Password/documentation/PasswordFramework/PasswordVerification":{"type":"topic","identifier":"doc:\/\/com.aheaditec.widgetizing.Password\/documentation\/PasswordFramework\/PasswordVerification","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PasswordVerification","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PasswordVerification"}],"abstract":[{"type":"text","text":"Class used for password verification. It allows cancellation and verification operations."}],"url":"\/documentation\/passwordframework\/passwordverification","title":"PasswordVerification","kind":"symbol"},"doc://com.aheaditec.widgetizing.Password/documentation/PasswordFramework/PasswordWidgetError":{"role":"symbol","abstract":[{"type":"text","text":"Represents an enum hierarchy for errors related to the widget."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PasswordWidgetError"}],"title":"PasswordWidgetError","type":"topic","identifier":"doc:\/\/com.aheaditec.widgetizing.Password\/documentation\/PasswordFramework\/PasswordWidgetError","kind":"symbol","navigatorTitle":[{"text":"PasswordWidgetError","kind":"identifier"}],"url":"\/documentation\/passwordframework\/passwordwidgeterror"},"doc://com.aheaditec.widgetizing.Password/documentation/PasswordFramework":{"identifier":"doc:\/\/com.aheaditec.widgetizing.Password\/documentation\/PasswordFramework","kind":"symbol","url":"\/documentation\/passwordframework","role":"collection","abstract":[],"type":"topic","title":"PasswordFramework"},"doc://com.aheaditec.widgetizing.Password/documentation/PasswordFramework/Password":{"kind":"symbol","identifier":"doc:\/\/com.aheaditec.widgetizing.Password\/documentation\/PasswordFramework\/Password","type":"topic","abstract":[{"type":"text","text":"Class responsible for password widget initialization."}],"url":"\/documentation\/passwordframework\/password","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Password"}],"title":"Password","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Password","kind":"identifier"}]},"doc://com.aheaditec.widgetizing.Password/documentation/PasswordFramework/InitResponseDataObject":{"identifier":"doc:\/\/com.aheaditec.widgetizing.Password\/documentation\/PasswordFramework\/InitResponseDataObject","url":"\/documentation\/passwordframework\/initresponsedataobject","kind":"symbol","role":"symbol","abstract":[{"text":"Models a successful execution of the request.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"InitResponseDataObject","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"InitResponseDataObject","kind":"identifier"}],"title":"InitResponseDataObject"},"doc://com.aheaditec.widgetizing.Password/documentation/PasswordFramework/PasswordVersionString":{"abstract":[{"type":"text","text":"Project version string for Password."}],"title":"PasswordVersionString","type":"topic","kind":"symbol","fragments":[{"text":"PasswordVersionString","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.aheaditec.widgetizing.Password\/documentation\/PasswordFramework\/PasswordVersionString","url":"\/documentation\/passwordframework\/passwordversionstring"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/topicSections","value":[{"title":"Variables","identifiers":["doc:\/\/com.aheaditec.widgetizing.Password\/documentation\/PasswordFramework\/PasswordVersionNumber","doc:\/\/com.aheaditec.widgetizing.Password\/documentation\/PasswordFramework\/PasswordVersionString"]}],"op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"}],"traits":[{"interfaceLanguage":"occ"}]}]}