{"topicSections":[{"title":"Classes","identifiers":["doc:\/\/com.aheaditec.widgetizing.WigetUtils\/documentation\/WidgetUtilsFramework\/JweCrypter","doc:\/\/com.aheaditec.widgetizing.WigetUtils\/documentation\/WidgetUtilsFramework\/NetworkService","doc:\/\/com.aheaditec.widgetizing.WigetUtils\/documentation\/WidgetUtilsFramework\/URLConstants","doc:\/\/com.aheaditec.widgetizing.WigetUtils\/documentation\/WidgetUtilsFramework\/Utils"]},{"title":"Protocols","identifiers":["doc:\/\/com.aheaditec.widgetizing.WigetUtils\/documentation\/WidgetUtilsFramework\/ExpiredError","doc:\/\/com.aheaditec.widgetizing.WigetUtils\/documentation\/WidgetUtilsFramework\/JsendWidgetError","doc:\/\/com.aheaditec.widgetizing.WigetUtils\/documentation\/WidgetUtilsFramework\/NetworkServiceable","doc:\/\/com.aheaditec.widgetizing.WigetUtils\/documentation\/WidgetUtilsFramework\/UnsupportedAlgTypeError"]},{"identifiers":["doc:\/\/com.aheaditec.widgetizing.WigetUtils\/documentation\/WidgetUtilsFramework\/Blocker","doc:\/\/com.aheaditec.widgetizing.WigetUtils\/documentation\/WidgetUtilsFramework\/EmptyData","doc:\/\/com.aheaditec.widgetizing.WigetUtils\/documentation\/WidgetUtilsFramework\/EmptyRequest","doc:\/\/com.aheaditec.widgetizing.WigetUtils\/documentation\/WidgetUtilsFramework\/EncryptionHeader","doc:\/\/com.aheaditec.widgetizing.WigetUtils\/documentation\/WidgetUtilsFramework\/Expiration"],"title":"Structures"},{"title":"Functions","identifiers":["doc:\/\/com.aheaditec.widgetizing.WigetUtils\/documentation\/WidgetUtilsFramework\/hash(password:algType:salt:nonce:)"]},{"identifiers":["doc:\/\/com.aheaditec.widgetizing.WigetUtils\/documentation\/WidgetUtilsFramework\/BlockerType","doc:\/\/com.aheaditec.widgetizing.WigetUtils\/documentation\/WidgetUtilsFramework\/HttpRequest"],"title":"Enumerations"},{"identifiers":["doc:\/\/com.aheaditec.widgetizing.WigetUtils\/documentation\/WidgetUtilsFramework\/Swift"],"title":"Extended Modules"}],"identifier":{"url":"doc:\/\/com.aheaditec.widgetizing.WigetUtils\/documentation\/WidgetUtilsFramework","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Framework","symbolKind":"module","title":"WidgetUtilsFramework","externalID":"WidgetUtilsFramework","modules":[{"name":"WidgetUtilsFramework"}],"role":"collection"},"sections":[],"hierarchy":{"paths":[[]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/widgetutilsframework"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/widgetutilsframework"]}],"references":{"doc://com.aheaditec.widgetizing.WigetUtils/documentation/WidgetUtilsFramework/UnsupportedAlgTypeError":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UnsupportedAlgTypeError","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"UnsupportedAlgTypeError"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.aheaditec.widgetizing.WigetUtils\/documentation\/WidgetUtilsFramework\/UnsupportedAlgTypeError","url":"\/documentation\/widgetutilsframework\/unsupportedalgtypeerror","type":"topic","role":"symbol","title":"UnsupportedAlgTypeError"},"doc://com.aheaditec.widgetizing.WigetUtils/documentation/WidgetUtilsFramework/WigetUtilsVersionNumber":{"type":"topic","abstract":[{"text":"Project version number for WigetUtils.","type":"text"}],"identifier":"doc:\/\/com.aheaditec.widgetizing.WigetUtils\/documentation\/WidgetUtilsFramework\/WigetUtilsVersionNumber","url":"\/documentation\/widgetutilsframework\/wigetutilsversionnumber","fragments":[{"text":"WigetUtilsVersionNumber","kind":"identifier"}],"title":"WigetUtilsVersionNumber","role":"symbol","kind":"symbol"},"doc://com.aheaditec.widgetizing.WigetUtils/documentation/WidgetUtilsFramework":{"role":"collection","identifier":"doc:\/\/com.aheaditec.widgetizing.WigetUtils\/documentation\/WidgetUtilsFramework","abstract":[],"kind":"symbol","url":"\/documentation\/widgetutilsframework","type":"topic","title":"WidgetUtilsFramework"},"doc://com.aheaditec.widgetizing.WigetUtils/documentation/WidgetUtilsFramework/EncryptionHeader":{"url":"\/documentation\/widgetutilsframework\/encryptionheader","abstract":[],"title":"EncryptionHeader","identifier":"doc:\/\/com.aheaditec.widgetizing.WigetUtils\/documentation\/WidgetUtilsFramework\/EncryptionHeader","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"EncryptionHeader"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EncryptionHeader"}]},"doc://com.aheaditec.widgetizing.WigetUtils/documentation/WidgetUtilsFramework/BlockerType":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BlockerType"}],"url":"\/documentation\/widgetutilsframework\/blockertype","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BlockerType"}],"abstract":[],"identifier":"doc:\/\/com.aheaditec.widgetizing.WigetUtils\/documentation\/WidgetUtilsFramework\/BlockerType","title":"BlockerType"},"doc://com.aheaditec.widgetizing.WigetUtils/documentation/WidgetUtilsFramework/URLConstants":{"title":"URLConstants","type":"topic","url":"\/documentation\/widgetutilsframework\/urlconstants","navigatorTitle":[{"text":"URLConstants","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.aheaditec.widgetizing.WigetUtils\/documentation\/WidgetUtilsFramework\/URLConstants","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"URLConstants","kind":"identifier"}]},"doc://com.aheaditec.widgetizing.WigetUtils/documentation/WidgetUtilsFramework/ExpiredError":{"url":"\/documentation\/widgetutilsframework\/expirederror","identifier":"doc:\/\/com.aheaditec.widgetizing.WigetUtils\/documentation\/WidgetUtilsFramework\/ExpiredError","title":"ExpiredError","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ExpiredError"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ExpiredError"}]},"doc://com.aheaditec.widgetizing.WigetUtils/documentation/WidgetUtilsFramework/HttpRequest":{"role":"symbol","navigatorTitle":[{"text":"HttpRequest","kind":"identifier"}],"url":"\/documentation\/widgetutilsframework\/httprequest","type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HttpRequest"}],"abstract":[],"identifier":"doc:\/\/com.aheaditec.widgetizing.WigetUtils\/documentation\/WidgetUtilsFramework\/HttpRequest","title":"HttpRequest"},"doc://com.aheaditec.widgetizing.WigetUtils/documentation/WidgetUtilsFramework/JsendWidgetError":{"abstract":[],"url":"\/documentation\/widgetutilsframework\/jsendwidgeterror","navigatorTitle":[{"text":"JsendWidgetError","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"JsendWidgetError","kind":"identifier"}],"identifier":"doc:\/\/com.aheaditec.widgetizing.WigetUtils\/documentation\/WidgetUtilsFramework\/JsendWidgetError","title":"JsendWidgetError","role":"symbol","kind":"symbol","type":"topic"},"doc://com.aheaditec.widgetizing.WigetUtils/documentation/WidgetUtilsFramework/Utils":{"title":"Utils","abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Utils","kind":"identifier"}],"url":"\/documentation\/widgetutilsframework\/utils","type":"topic","identifier":"doc:\/\/com.aheaditec.widgetizing.WigetUtils\/documentation\/WidgetUtilsFramework\/Utils","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Utils"}]},"doc://com.aheaditec.widgetizing.WigetUtils/documentation/WidgetUtilsFramework/JweCrypter":{"url":"\/documentation\/widgetutilsframework\/jwecrypter","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JweCrypter","kind":"identifier"}],"abstract":[{"type":"text","text":"Encapsulating class for operations related to JWE."}],"role":"symbol","title":"JweCrypter","navigatorTitle":[{"text":"JweCrypter","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.aheaditec.widgetizing.WigetUtils\/documentation\/WidgetUtilsFramework\/JweCrypter"},"doc://com.aheaditec.widgetizing.WigetUtils/documentation/WidgetUtilsFramework/Swift":{"type":"topic","url":"\/documentation\/widgetutilsframework\/swift","role":"collection","kind":"symbol","title":"Swift","identifier":"doc:\/\/com.aheaditec.widgetizing.WigetUtils\/documentation\/WidgetUtilsFramework\/Swift","abstract":[]},"doc://com.aheaditec.widgetizing.WigetUtils/documentation/WidgetUtilsFramework/NetworkService":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NetworkService"}],"abstract":[],"title":"NetworkService","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NetworkService","kind":"identifier"}],"identifier":"doc:\/\/com.aheaditec.widgetizing.WigetUtils\/documentation\/WidgetUtilsFramework\/NetworkService","url":"\/documentation\/widgetutilsframework\/networkservice","role":"symbol"},"doc://com.aheaditec.widgetizing.WigetUtils/documentation/WidgetUtilsFramework/WigetUtilsVersionString":{"abstract":[{"type":"text","text":"Project version string for WigetUtils."}],"url":"\/documentation\/widgetutilsframework\/wigetutilsversionstring","type":"topic","fragments":[{"kind":"identifier","text":"WigetUtilsVersionString"}],"kind":"symbol","title":"WigetUtilsVersionString","role":"symbol","identifier":"doc:\/\/com.aheaditec.widgetizing.WigetUtils\/documentation\/WidgetUtilsFramework\/WigetUtilsVersionString"},"doc://com.aheaditec.widgetizing.WigetUtils/documentation/WidgetUtilsFramework/EmptyRequest":{"navigatorTitle":[{"text":"EmptyRequest","kind":"identifier"}],"abstract":[],"kind":"symbol","title":"EmptyRequest","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EmptyRequest","kind":"identifier"}],"identifier":"doc:\/\/com.aheaditec.widgetizing.WigetUtils\/documentation\/WidgetUtilsFramework\/EmptyRequest","type":"topic","url":"\/documentation\/widgetutilsframework\/emptyrequest"},"doc://com.aheaditec.widgetizing.WigetUtils/documentation/WidgetUtilsFramework/Blocker":{"url":"\/documentation\/widgetutilsframework\/blocker","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Blocker"}],"type":"topic","identifier":"doc:\/\/com.aheaditec.widgetizing.WigetUtils\/documentation\/WidgetUtilsFramework\/Blocker","kind":"symbol","title":"Blocker","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"Blocker","kind":"identifier"}]},"doc://com.aheaditec.widgetizing.WigetUtils/documentation/WidgetUtilsFramework/NetworkServiceable":{"url":"\/documentation\/widgetutilsframework\/networkserviceable","type":"topic","identifier":"doc:\/\/com.aheaditec.widgetizing.WigetUtils\/documentation\/WidgetUtilsFramework\/NetworkServiceable","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"NetworkServiceable","kind":"identifier"}],"role":"symbol","title":"NetworkServiceable","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetworkServiceable"}]},"doc://com.aheaditec.widgetizing.WigetUtils/documentation/WidgetUtilsFramework/Expiration":{"kind":"symbol","identifier":"doc:\/\/com.aheaditec.widgetizing.WigetUtils\/documentation\/WidgetUtilsFramework\/Expiration","navigatorTitle":[{"text":"Expiration","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"An object representing a point in time after which something happens, typically a transaction\/blocker expires, etc."}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"Expiration","kind":"identifier"}],"type":"topic","url":"\/documentation\/widgetutilsframework\/expiration","title":"Expiration"},"doc://com.aheaditec.widgetizing.WigetUtils/documentation/WidgetUtilsFramework/EmptyData":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"EmptyData","kind":"identifier"}],"type":"topic","url":"\/documentation\/widgetutilsframework\/emptydata","navigatorTitle":[{"kind":"identifier","text":"EmptyData"}],"kind":"symbol","identifier":"doc:\/\/com.aheaditec.widgetizing.WigetUtils\/documentation\/WidgetUtilsFramework\/EmptyData","role":"symbol","title":"EmptyData","abstract":[]},"doc://com.aheaditec.widgetizing.WigetUtils/documentation/WidgetUtilsFramework/hash(password:algType:salt:nonce:)":{"kind":"symbol","identifier":"doc:\/\/com.aheaditec.widgetizing.WigetUtils\/documentation\/WidgetUtilsFramework\/hash(password:algType:salt:nonce:)","abstract":[],"role":"symbol","title":"hash(password:algType:salt:nonce:)","url":"\/documentation\/widgetutilsframework\/hash(password:algtype:salt:nonce:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"text":"<","kind":"text"},{"kind":"genericParameter","text":"E"},{"kind":"text","text":">("},{"text":"password","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"algType","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"text":"?, ","kind":"text"},{"text":"salt","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"nonce","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"text":") -> Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"E","preciseIdentifier":"s:20WidgetUtilsFramework4hash8password7algType4salt5nonces6ResultOySSxGSS_SuSg10Foundation4DataVAMtAA014UnsupportedAlgG5ErrorRzlF1EL_xmfp"},{"text":">","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Variables","identifiers":["doc:\/\/com.aheaditec.widgetizing.WigetUtils\/documentation\/WidgetUtilsFramework\/WigetUtilsVersionNumber","doc:\/\/com.aheaditec.widgetizing.WigetUtils\/documentation\/WidgetUtilsFramework\/WigetUtilsVersionString"]}]},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null}]}]}