{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/aqridentifysupportframework"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/aqridentifysupportframework"]}],"metadata":{"title":"AQRIdentifySupportFramework","symbolKind":"module","roleHeading":"Framework","role":"collection","externalID":"AQRIdentifySupportFramework","modules":[{"name":"AQRIdentifySupportFramework"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[[]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.aheaditec.widgetizing.AQRIdentifySupport\/documentation\/AQRIdentifySupportFramework"},"topicSections":[{"identifiers":["doc:\/\/com.aheaditec.widgetizing.AQRIdentifySupport\/documentation\/AQRIdentifySupportFramework\/AQRIdentify"],"title":"Structures"},{"title":"Type Aliases","identifiers":["doc:\/\/com.aheaditec.widgetizing.AQRIdentifySupport\/documentation\/AQRIdentifySupportFramework\/AQRIdentifyError"]},{"identifiers":["doc:\/\/com.aheaditec.widgetizing.AQRIdentifySupport\/documentation\/AQRIdentifySupportFramework\/AQRIdentifyURLExtensionError"],"title":"Enumerations"},{"identifiers":["doc:\/\/com.aheaditec.widgetizing.AQRIdentifySupport\/documentation\/AQRIdentifySupportFramework\/Foundation"],"title":"Extended Modules"}],"references":{"doc://com.aheaditec.widgetizing.AQRIdentifySupport/documentation/AQRIdentifySupportFramework/AQRIdentifyURLExtensionError":{"identifier":"doc:\/\/com.aheaditec.widgetizing.AQRIdentifySupport\/documentation\/AQRIdentifySupportFramework\/AQRIdentifyURLExtensionError","title":"AQRIdentifyURLExtensionError","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AQRIdentifyURLExtensionError"}],"navigatorTitle":[{"kind":"identifier","text":"AQRIdentifyURLExtensionError"}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/aqridentifysupportframework\/aqridentifyurlextensionerror"},"doc://com.aheaditec.widgetizing.AQRIdentifySupport/documentation/AQRIdentifySupportFramework/AQRIdentify":{"abstract":[{"text":"Component to handle AQR identify process to get transaction id","type":"text"}],"url":"\/documentation\/aqridentifysupportframework\/aqridentify","navigatorTitle":[{"text":"AQRIdentify","kind":"identifier"}],"title":"AQRIdentify","role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AQRIdentify"}],"identifier":"doc:\/\/com.aheaditec.widgetizing.AQRIdentifySupport\/documentation\/AQRIdentifySupportFramework\/AQRIdentify"},"doc://com.aheaditec.widgetizing.AQRIdentifySupport/documentation/AQRIdentifySupportFramework":{"title":"AQRIdentifySupportFramework","identifier":"doc:\/\/com.aheaditec.widgetizing.AQRIdentifySupport\/documentation\/AQRIdentifySupportFramework","abstract":[],"role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/aqridentifysupportframework"},"doc://com.aheaditec.widgetizing.AQRIdentifySupport/documentation/AQRIdentifySupportFramework/Foundation":{"type":"topic","url":"\/documentation\/aqridentifysupportframework\/foundation","abstract":[],"identifier":"doc:\/\/com.aheaditec.widgetizing.AQRIdentifySupport\/documentation\/AQRIdentifySupportFramework\/Foundation","kind":"symbol","title":"Foundation","role":"collection"},"doc://com.aheaditec.widgetizing.AQRIdentifySupport/documentation/AQRIdentifySupportFramework/AQRIdentifySupportVersionNumber":{"kind":"symbol","title":"AQRIdentifySupportVersionNumber","abstract":[{"text":"Project version number for AQRIdentifySupport.","type":"text"}],"role":"symbol","type":"topic","url":"\/documentation\/aqridentifysupportframework\/aqridentifysupportversionnumber","fragments":[{"text":"AQRIdentifySupportVersionNumber","kind":"identifier"}],"identifier":"doc:\/\/com.aheaditec.widgetizing.AQRIdentifySupport\/documentation\/AQRIdentifySupportFramework\/AQRIdentifySupportVersionNumber"},"doc://com.aheaditec.widgetizing.AQRIdentifySupport/documentation/AQRIdentifySupportFramework/AQRIdentifyError":{"title":"AQRIdentifyError","role":"symbol","abstract":[],"type":"topic","url":"\/documentation\/aqridentifysupportframework\/aqridentifyerror","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AQRIdentifyError"}],"identifier":"doc:\/\/com.aheaditec.widgetizing.AQRIdentifySupport\/documentation\/AQRIdentifySupportFramework\/AQRIdentifyError","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AQRIdentifyError"}]},"doc://com.aheaditec.widgetizing.AQRIdentifySupport/documentation/AQRIdentifySupportFramework/AQRIdentifySupportVersionString":{"fragments":[{"kind":"identifier","text":"AQRIdentifySupportVersionString"}],"kind":"symbol","abstract":[{"text":"Project version string for AQRIdentifySupport.","type":"text"}],"role":"symbol","title":"AQRIdentifySupportVersionString","url":"\/documentation\/aqridentifysupportframework\/aqridentifysupportversionstring","type":"topic","identifier":"doc:\/\/com.aheaditec.widgetizing.AQRIdentifySupport\/documentation\/AQRIdentifySupportFramework\/AQRIdentifySupportVersionString"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.aheaditec.widgetizing.AQRIdentifySupport\/documentation\/AQRIdentifySupportFramework\/AQRIdentifySupportVersionNumber","doc:\/\/com.aheaditec.widgetizing.AQRIdentifySupport\/documentation\/AQRIdentifySupportFramework\/AQRIdentifySupportVersionString"],"title":"Variables"}],"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"}],"traits":[{"interfaceLanguage":"occ"}]}]}