{"identifier":{"url":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"content","content":[{"type":"heading","level":2,"anchor":"Overview","text":"Overview"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/passwordandnfinityframework"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/passwordandnfinityframework"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[[]]},"kind":"symbol","topicSections":[{"title":"Classes","identifiers":["doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/DocumentScan","doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/FaceDetectionSender","doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/FaceScan","doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/FaceScanPolling","doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/LivenessCheck","doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/LivenessCheckVerification","doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/Password","doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/PasswordAndNfinity","doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/WidgetCommons","doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/WidgetCommonsWithEncrypted"]},{"title":"Structures","identifiers":["doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/AppParam","doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/ConfigResponse","doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudErrorResponse","doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/ProcessConfig"]},{"title":"Enumerations","identifiers":["doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/Corner","doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/FaceDetectionState","doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/Instruction","doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/LivenessCheckVerificationState","doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudError","doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityState","doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/PasswordAndNfinityWidgetError","doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/PollWithVerifyState","doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/UseCase"]}],"metadata":{"role":"collection","title":"PasswordAndNfinityFramework","modules":[{"name":"PasswordAndNfinityFramework"}],"roleHeading":"Framework","externalID":"PasswordAndNfinityFramework","symbolKind":"module"},"references":{"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework/WidgetCommonsWithEncrypted":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"WidgetCommonsWithEncrypted","kind":"identifier"}],"title":"WidgetCommonsWithEncrypted","url":"\/documentation\/passwordandnfinityframework\/widgetcommonswithencrypted","role":"symbol","identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/WidgetCommonsWithEncrypted","navigatorTitle":[{"kind":"identifier","text":"WidgetCommonsWithEncrypted"}],"abstract":[],"kind":"symbol"},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework/PasswordAndNfinityWidgetError":{"url":"\/documentation\/passwordandnfinityframework\/passwordandnfinitywidgeterror","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PasswordAndNfinityWidgetError","kind":"identifier"}],"abstract":[{"type":"text","text":"Represents an enum hierarchy for errors related to the widget."}],"kind":"symbol","title":"PasswordAndNfinityWidgetError","identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/PasswordAndNfinityWidgetError","type":"topic","role":"symbol","navigatorTitle":[{"text":"PasswordAndNfinityWidgetError","kind":"identifier"}]},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework/ProcessConfig":{"title":"ProcessConfig","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"ProcessConfig","kind":"identifier"}],"abstract":[{"text":"Process configuration","type":"text"}],"url":"\/documentation\/passwordandnfinityframework\/processconfig","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ProcessConfig"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/ProcessConfig"},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework/Password":{"role":"symbol","type":"topic","title":"Password","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Password"}],"identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/Password","url":"\/documentation\/passwordandnfinityframework\/password","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Password","kind":"identifier"}]},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework/LivenessCheck":{"identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/LivenessCheck","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"LivenessCheck","kind":"identifier"}],"url":"\/documentation\/passwordandnfinityframework\/livenesscheck","type":"topic","navigatorTitle":[{"text":"LivenessCheck","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Class responsible for getting liveness path from Nfinity Cloud."}],"title":"LivenessCheck"},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework":{"url":"\/documentation\/passwordandnfinityframework","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework","title":"PasswordAndNfinityFramework","type":"topic","role":"collection"},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework/PasswordAndNfinityFrameworkVersionNumber":{"type":"topic","abstract":[{"type":"text","text":"Project version number for PasswordAndNfinityFramework."}],"fragments":[{"text":"PasswordAndNfinityFrameworkVersionNumber","kind":"identifier"}],"identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/PasswordAndNfinityFrameworkVersionNumber","url":"\/documentation\/passwordandnfinityframework\/passwordandnfinityframeworkversionnumber","kind":"symbol","role":"symbol","title":"PasswordAndNfinityFrameworkVersionNumber"},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework/LivenessCheckVerification":{"abstract":[{"text":"Class responsible for verifying liveness via Nfinity Cloud.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LivenessCheckVerification","kind":"identifier"}],"title":"LivenessCheckVerification","navigatorTitle":[{"text":"LivenessCheckVerification","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/LivenessCheckVerification","url":"\/documentation\/passwordandnfinityframework\/livenesscheckverification"},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework/PollWithVerifyState":{"type":"topic","identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/PollWithVerifyState","navigatorTitle":[{"kind":"identifier","text":"PollWithVerifyState"}],"url":"\/documentation\/passwordandnfinityframework\/pollwithverifystate","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PollWithVerifyState","kind":"identifier"}],"abstract":[{"type":"text","text":"Response state after polling and verifing."}],"kind":"symbol","title":"PollWithVerifyState"},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework/PasswordAndNfinity":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PasswordAndNfinity","kind":"identifier"}],"identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/PasswordAndNfinity","kind":"symbol","role":"symbol","url":"\/documentation\/passwordandnfinityframework\/passwordandnfinity","abstract":[{"type":"text","text":"Class responsible for PasswordAndNfinity widget initialization."}],"navigatorTitle":[{"text":"PasswordAndNfinity","kind":"identifier"}],"title":"PasswordAndNfinity"},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework/DocumentScan":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DocumentScan","kind":"identifier"}],"identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/DocumentScan","url":"\/documentation\/passwordandnfinityframework\/documentscan","title":"DocumentScan","abstract":[{"text":"Class responsible for verifying documents.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"DocumentScan","kind":"identifier"}]},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework/LivenessCheckVerificationState":{"identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/LivenessCheckVerificationState","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LivenessCheckVerificationState"}],"url":"\/documentation\/passwordandnfinityframework\/livenesscheckverificationstate","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LivenessCheckVerificationState"}],"kind":"symbol","abstract":[{"type":"text","text":"Response state after checking liveness."}],"title":"LivenessCheckVerificationState"},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework/FaceScan":{"navigatorTitle":[{"kind":"identifier","text":"FaceScan"}],"title":"FaceScan","role":"symbol","abstract":[{"type":"text","text":"Class responsible for initializing face scan sequence at Nfinity Cloud."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceScan","kind":"identifier"}],"type":"topic","url":"\/documentation\/passwordandnfinityframework\/facescan","kind":"symbol","identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/FaceScan"},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework/Instruction":{"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Instruction","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Instruction"}],"abstract":[],"identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/Instruction","url":"\/documentation\/passwordandnfinityframework\/instruction","title":"Instruction"},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework/AppParam":{"navigatorTitle":[{"text":"AppParam","kind":"identifier"}],"identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/AppParam","url":"\/documentation\/passwordandnfinityframework\/appparam","type":"topic","abstract":[{"text":"AppParam","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppParam"}],"kind":"symbol","title":"AppParam","role":"symbol"},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework/ConfigResponse":{"identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/ConfigResponse","abstract":[{"text":"Configuration attributes for client application","type":"text"}],"title":"ConfigResponse","url":"\/documentation\/passwordandnfinityframework\/configresponse","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"ConfigResponse","kind":"identifier"}],"navigatorTitle":[{"text":"ConfigResponse","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework/NfinityState":{"kind":"symbol","identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityState","abstract":[{"text":"Response state after password encrypting.","type":"text"}],"role":"symbol","url":"\/documentation\/passwordandnfinityframework\/nfinitystate","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"NfinityState","kind":"identifier"}],"navigatorTitle":[{"text":"NfinityState","kind":"identifier"}],"title":"NfinityState"},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework/WidgetCommons":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WidgetCommons","kind":"identifier"}],"url":"\/documentation\/passwordandnfinityframework\/widgetcommons","navigatorTitle":[{"text":"WidgetCommons","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","title":"WidgetCommons","abstract":[],"identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/WidgetCommons"},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework/UseCase":{"navigatorTitle":[{"text":"UseCase","kind":"identifier"}],"type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"UseCase"}],"kind":"symbol","url":"\/documentation\/passwordandnfinityframework\/usecase","role":"symbol","title":"UseCase","identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/UseCase"},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework/PasswordAndNfinityFrameworkVersionString":{"identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/PasswordAndNfinityFrameworkVersionString","kind":"symbol","fragments":[{"text":"PasswordAndNfinityFrameworkVersionString","kind":"identifier"}],"abstract":[{"text":"Project version string for PasswordAndNfinityFramework.","type":"text"}],"url":"\/documentation\/passwordandnfinityframework\/passwordandnfinityframeworkversionstring","type":"topic","title":"PasswordAndNfinityFrameworkVersionString","role":"symbol"},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework/FaceDetectionState":{"navigatorTitle":[{"text":"FaceDetectionState","kind":"identifier"}],"type":"topic","abstract":[{"text":"Response state after face detection.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceDetectionState"}],"kind":"symbol","url":"\/documentation\/passwordandnfinityframework\/facedetectionstate","role":"symbol","title":"FaceDetectionState","identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/FaceDetectionState"},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework/Corner":{"kind":"symbol","identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/Corner","url":"\/documentation\/passwordandnfinityframework\/corner","title":"Corner","abstract":[],"navigatorTitle":[{"text":"Corner","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Corner"}]},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework/FaceScanPolling":{"type":"topic","abstract":[{"text":"Class responsible of face scan polling and verifying.","type":"text"}],"identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/FaceScanPolling","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceScanPolling","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"FaceScanPolling","kind":"identifier"}],"url":"\/documentation\/passwordandnfinityframework\/facescanpolling","title":"FaceScanPolling"},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework/NfinityCloudErrorResponse":{"abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NfinityCloudErrorResponse"}],"type":"topic","title":"NfinityCloudErrorResponse","identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudErrorResponse","url":"\/documentation\/passwordandnfinityframework\/nfinityclouderrorresponse","kind":"symbol","navigatorTitle":[{"text":"NfinityCloudErrorResponse","kind":"identifier"}],"role":"symbol"},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework/NfinityCloudError":{"abstract":[{"text":"Represents an enum hierarchy for errors related to the Nfinity Cloud.","type":"text"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NfinityCloudError"}],"identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudError","navigatorTitle":[{"text":"NfinityCloudError","kind":"identifier"}],"role":"symbol","title":"NfinityCloudError","url":"\/documentation\/passwordandnfinityframework\/nfinityclouderror"},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework/FaceDetectionSender":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceDetectionSender"}],"title":"FaceDetectionSender","url":"\/documentation\/passwordandnfinityframework\/facedetectionsender","role":"symbol","identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/FaceDetectionSender","navigatorTitle":[{"text":"FaceDetectionSender","kind":"identifier"}],"abstract":[{"type":"text","text":"Class responsible for sending face detection to Nfinity Cloud."}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":[{"identifiers":["doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/PasswordAndNfinityFrameworkVersionNumber","doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/PasswordAndNfinityFrameworkVersionString"],"title":"Variables"}],"path":"\/topicSections","op":"replace"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"}],"traits":[{"interfaceLanguage":"occ"}]}]}