{"hierarchy":{"paths":[[]]},"kind":"symbol","topicSections":[{"title":"Classes","identifiers":["doc:\/\/com.aheaditec.widgetizing.SoftwareToken\/documentation\/SoftwareTokenFramework\/SoftwareToken","doc:\/\/com.aheaditec.widgetizing.SoftwareToken\/documentation\/SoftwareTokenFramework\/SoftwareTokenVerification"]},{"title":"Structures","identifiers":["doc:\/\/com.aheaditec.widgetizing.SoftwareToken\/documentation\/SoftwareTokenFramework\/InitResponseDataObject","doc:\/\/com.aheaditec.widgetizing.SoftwareToken\/documentation\/SoftwareTokenFramework\/WidgetState"]},{"title":"Enumerations","identifiers":["doc:\/\/com.aheaditec.widgetizing.SoftwareToken\/documentation\/SoftwareTokenFramework\/SoftwareTokenPollState","doc:\/\/com.aheaditec.widgetizing.SoftwareToken\/documentation\/SoftwareTokenFramework\/SoftwareTokenWidgetError"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/softwaretokenframework"]},{"paths":["\/documentation\/softwaretokenframework"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"modules":[{"name":"SoftwareTokenFramework"}],"title":"SoftwareTokenFramework","symbolKind":"module","role":"collection","roleHeading":"Framework","externalID":"SoftwareTokenFramework"},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.aheaditec.widgetizing.SoftwareToken\/documentation\/SoftwareTokenFramework"},"references":{"doc://com.aheaditec.widgetizing.SoftwareToken/documentation/SoftwareTokenFramework/SoftwareTokenVersionString":{"fragments":[{"kind":"identifier","text":"SoftwareTokenVersionString"}],"abstract":[{"type":"text","text":"Project version string for SoftwareToken."}],"role":"symbol","url":"\/documentation\/softwaretokenframework\/softwaretokenversionstring","title":"SoftwareTokenVersionString","type":"topic","identifier":"doc:\/\/com.aheaditec.widgetizing.SoftwareToken\/documentation\/SoftwareTokenFramework\/SoftwareTokenVersionString","kind":"symbol"},"doc://com.aheaditec.widgetizing.SoftwareToken/documentation/SoftwareTokenFramework/SoftwareTokenPollState":{"title":"SoftwareTokenPollState","url":"\/documentation\/softwaretokenframework\/softwaretokenpollstate","type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SoftwareTokenPollState"}],"abstract":[],"navigatorTitle":[{"text":"SoftwareTokenPollState","kind":"identifier"}],"identifier":"doc:\/\/com.aheaditec.widgetizing.SoftwareToken\/documentation\/SoftwareTokenFramework\/SoftwareTokenPollState"},"doc://com.aheaditec.widgetizing.SoftwareToken/documentation/SoftwareTokenFramework/SoftwareToken":{"identifier":"doc:\/\/com.aheaditec.widgetizing.SoftwareToken\/documentation\/SoftwareTokenFramework\/SoftwareToken","navigatorTitle":[{"kind":"identifier","text":"SoftwareToken"}],"title":"SoftwareToken","abstract":[{"text":"Initial class in SoftwareToken widget call sequence","type":"text"}],"type":"topic","url":"\/documentation\/softwaretokenframework\/softwaretoken","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SoftwareToken"}]},"doc://com.aheaditec.widgetizing.SoftwareToken/documentation/SoftwareTokenFramework/SoftwareTokenVerification":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SoftwareTokenVerification"}],"title":"SoftwareTokenVerification","abstract":[{"type":"text","text":"A class responsible for Software Token verification."}],"url":"\/documentation\/softwaretokenframework\/softwaretokenverification","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SoftwareTokenVerification","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.aheaditec.widgetizing.SoftwareToken\/documentation\/SoftwareTokenFramework\/SoftwareTokenVerification","role":"symbol"},"doc://com.aheaditec.widgetizing.SoftwareToken/documentation/SoftwareTokenFramework/SoftwareTokenVersionNumber":{"fragments":[{"kind":"identifier","text":"SoftwareTokenVersionNumber"}],"url":"\/documentation\/softwaretokenframework\/softwaretokenversionnumber","abstract":[{"type":"text","text":"Project version number for SoftwareToken."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.aheaditec.widgetizing.SoftwareToken\/documentation\/SoftwareTokenFramework\/SoftwareTokenVersionNumber","title":"SoftwareTokenVersionNumber","type":"topic"},"doc://com.aheaditec.widgetizing.SoftwareToken/documentation/SoftwareTokenFramework/SoftwareTokenWidgetError":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SoftwareTokenWidgetError"}],"type":"topic","identifier":"doc:\/\/com.aheaditec.widgetizing.SoftwareToken\/documentation\/SoftwareTokenFramework\/SoftwareTokenWidgetError","navigatorTitle":[{"kind":"identifier","text":"SoftwareTokenWidgetError"}],"abstract":[{"type":"text","text":"Represents an enum hierarchy for errors related to the widget."}],"title":"SoftwareTokenWidgetError","url":"\/documentation\/softwaretokenframework\/softwaretokenwidgeterror","kind":"symbol"},"doc://com.aheaditec.widgetizing.SoftwareToken/documentation/SoftwareTokenFramework/InitResponseDataObject":{"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"InitResponseDataObject","kind":"identifier"}],"abstract":[{"type":"text","text":"Models a successful execution of the request."}],"navigatorTitle":[{"text":"InitResponseDataObject","kind":"identifier"}],"role":"symbol","url":"\/documentation\/softwaretokenframework\/initresponsedataobject","title":"InitResponseDataObject","type":"topic","identifier":"doc:\/\/com.aheaditec.widgetizing.SoftwareToken\/documentation\/SoftwareTokenFramework\/InitResponseDataObject","kind":"symbol"},"doc://com.aheaditec.widgetizing.SoftwareToken/documentation/SoftwareTokenFramework/WidgetState":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.aheaditec.widgetizing.SoftwareToken\/documentation\/SoftwareTokenFramework\/WidgetState","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WidgetState"}],"title":"WidgetState","abstract":[{"type":"text","text":"Current state of the widget, can be used to initialize "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.aheaditec.widgetizing.SoftwareToken\/documentation\/SoftwareTokenFramework\/SoftwareTokenVerification"},{"text":" class.","type":"text"}],"url":"\/documentation\/softwaretokenframework\/widgetstate","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetState"}]},"doc://com.aheaditec.widgetizing.SoftwareToken/documentation/SoftwareTokenFramework":{"title":"SoftwareTokenFramework","url":"\/documentation\/softwaretokenframework","type":"topic","role":"collection","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.aheaditec.widgetizing.SoftwareToken\/documentation\/SoftwareTokenFramework"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":[{"title":"Variables","identifiers":["doc:\/\/com.aheaditec.widgetizing.SoftwareToken\/documentation\/SoftwareTokenFramework\/SoftwareTokenVersionNumber","doc:\/\/com.aheaditec.widgetizing.SoftwareToken\/documentation\/SoftwareTokenFramework\/SoftwareTokenVersionString"]}],"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"}],"traits":[{"interfaceLanguage":"occ"}]}]}