{"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"identifiers":["doc:\/\/com.aheaditec.widgetizing.TransactionProcessor\/documentation\/TransactionProcessorFramework\/GeneralProcessorParameters","doc:\/\/com.aheaditec.widgetizing.TransactionProcessor\/documentation\/TransactionProcessorFramework\/InProgressProcessorParameters","doc:\/\/com.aheaditec.widgetizing.TransactionProcessor\/documentation\/TransactionProcessorFramework\/TransactionProcessorClient"],"title":"Classes"},{"title":"Structures","identifiers":["doc:\/\/com.aheaditec.widgetizing.TransactionProcessor\/documentation\/TransactionProcessorFramework\/Expiration","doc:\/\/com.aheaditec.widgetizing.TransactionProcessor\/documentation\/TransactionProcessorFramework\/GetProcessorDataObject","doc:\/\/com.aheaditec.widgetizing.TransactionProcessor\/documentation\/TransactionProcessorFramework\/ProcessorWidget","doc:\/\/com.aheaditec.widgetizing.TransactionProcessor\/documentation\/TransactionProcessorFramework\/ProcessorWidgetScenario","doc:\/\/com.aheaditec.widgetizing.TransactionProcessor\/documentation\/TransactionProcessorFramework\/Reason","doc:\/\/com.aheaditec.widgetizing.TransactionProcessor\/documentation\/TransactionProcessorFramework\/SetLocaleDataObject","doc:\/\/com.aheaditec.widgetizing.TransactionProcessor\/documentation\/TransactionProcessorFramework\/TransactionProcessorState","doc:\/\/com.aheaditec.widgetizing.TransactionProcessor\/documentation\/TransactionProcessorFramework\/UnavailableProcessorWidget"]},{"title":"Enumerations","identifiers":["doc:\/\/com.aheaditec.widgetizing.TransactionProcessor\/documentation\/TransactionProcessorFramework\/ProcessorState","doc:\/\/com.aheaditec.widgetizing.TransactionProcessor\/documentation\/TransactionProcessorFramework\/TransactionProcessorError"]}],"hierarchy":{"paths":[[]]},"metadata":{"role":"collection","externalID":"TransactionProcessorFramework","modules":[{"name":"TransactionProcessorFramework"}],"title":"TransactionProcessorFramework","symbolKind":"module","roleHeading":"Framework"},"identifier":{"url":"doc:\/\/com.aheaditec.widgetizing.TransactionProcessor\/documentation\/TransactionProcessorFramework","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/transactionprocessorframework"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/transactionprocessorframework"]}],"sections":[],"references":{"doc://com.aheaditec.widgetizing.TransactionProcessor/documentation/TransactionProcessorFramework/GeneralProcessorParameters":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GeneralProcessorParameters","kind":"identifier"}],"type":"topic","abstract":[],"identifier":"doc:\/\/com.aheaditec.widgetizing.TransactionProcessor\/documentation\/TransactionProcessorFramework\/GeneralProcessorParameters","url":"\/documentation\/transactionprocessorframework\/generalprocessorparameters","navigatorTitle":[{"kind":"identifier","text":"GeneralProcessorParameters"}],"role":"symbol","title":"GeneralProcessorParameters","kind":"symbol"},"doc://com.aheaditec.widgetizing.TransactionProcessor/documentation/TransactionProcessorFramework/ProcessorWidgetScenario":{"identifier":"doc:\/\/com.aheaditec.widgetizing.TransactionProcessor\/documentation\/TransactionProcessorFramework\/ProcessorWidgetScenario","kind":"symbol","abstract":[],"title":"ProcessorWidgetScenario","navigatorTitle":[{"text":"ProcessorWidgetScenario","kind":"identifier"}],"type":"topic","url":"\/documentation\/transactionprocessorframework\/processorwidgetscenario","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ProcessorWidgetScenario"}],"role":"symbol"},"doc://com.aheaditec.widgetizing.TransactionProcessor/documentation/TransactionProcessorFramework/ProcessorWidget":{"title":"ProcessorWidget","type":"topic","url":"\/documentation\/transactionprocessorframework\/processorwidget","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ProcessorWidget"}],"identifier":"doc:\/\/com.aheaditec.widgetizing.TransactionProcessor\/documentation\/TransactionProcessorFramework\/ProcessorWidget","navigatorTitle":[{"kind":"identifier","text":"ProcessorWidget"}],"role":"symbol","kind":"symbol"},"doc://com.aheaditec.widgetizing.TransactionProcessor/documentation/TransactionProcessorFramework/Reason":{"role":"symbol","identifier":"doc:\/\/com.aheaditec.widgetizing.TransactionProcessor\/documentation\/TransactionProcessorFramework\/Reason","navigatorTitle":[{"kind":"identifier","text":"Reason"}],"title":"Reason","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Reason"}],"kind":"symbol","abstract":[],"url":"\/documentation\/transactionprocessorframework\/reason","type":"topic"},"doc://com.aheaditec.widgetizing.TransactionProcessor/documentation/TransactionProcessorFramework/InProgressProcessorParameters":{"role":"symbol","identifier":"doc:\/\/com.aheaditec.widgetizing.TransactionProcessor\/documentation\/TransactionProcessorFramework\/InProgressProcessorParameters","navigatorTitle":[{"kind":"identifier","text":"InProgressProcessorParameters"}],"title":"InProgressProcessorParameters","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"InProgressProcessorParameters"}],"kind":"symbol","abstract":[],"url":"\/documentation\/transactionprocessorframework\/inprogressprocessorparameters","type":"topic"},"doc://com.aheaditec.widgetizing.TransactionProcessor/documentation/TransactionProcessorFramework/TransactionProcessorError":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TransactionProcessorError"}],"identifier":"doc:\/\/com.aheaditec.widgetizing.TransactionProcessor\/documentation\/TransactionProcessorFramework\/TransactionProcessorError","abstract":[],"navigatorTitle":[{"text":"TransactionProcessorError","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"TransactionProcessorError","type":"topic","url":"\/documentation\/transactionprocessorframework\/transactionprocessorerror"},"doc://com.aheaditec.widgetizing.TransactionProcessor/documentation/TransactionProcessorFramework/TransactionProcessorVersionNumber":{"role":"symbol","title":"TransactionProcessorVersionNumber","fragments":[{"kind":"identifier","text":"TransactionProcessorVersionNumber"}],"type":"topic","abstract":[{"text":"Project version number for TransactionProcessor.","type":"text"}],"url":"\/documentation\/transactionprocessorframework\/transactionprocessorversionnumber","kind":"symbol","identifier":"doc:\/\/com.aheaditec.widgetizing.TransactionProcessor\/documentation\/TransactionProcessorFramework\/TransactionProcessorVersionNumber"},"doc://com.aheaditec.widgetizing.TransactionProcessor/documentation/TransactionProcessorFramework/UnavailableProcessorWidget":{"title":"UnavailableProcessorWidget","role":"symbol","url":"\/documentation\/transactionprocessorframework\/unavailableprocessorwidget","identifier":"doc:\/\/com.aheaditec.widgetizing.TransactionProcessor\/documentation\/TransactionProcessorFramework\/UnavailableProcessorWidget","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"UnavailableProcessorWidget","kind":"identifier"}],"abstract":[],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UnavailableProcessorWidget"}]},"doc://com.aheaditec.widgetizing.TransactionProcessor/documentation/TransactionProcessorFramework/TransactionProcessorVersionString":{"fragments":[{"text":"TransactionProcessorVersionString","kind":"identifier"}],"abstract":[{"text":"Project version string for TransactionProcessor.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.aheaditec.widgetizing.TransactionProcessor\/documentation\/TransactionProcessorFramework\/TransactionProcessorVersionString","title":"TransactionProcessorVersionString","kind":"symbol","url":"\/documentation\/transactionprocessorframework\/transactionprocessorversionstring","role":"symbol"},"doc://com.aheaditec.widgetizing.TransactionProcessor/documentation/TransactionProcessorFramework/GetProcessorDataObject":{"abstract":[],"type":"topic","url":"\/documentation\/transactionprocessorframework\/getprocessordataobject","identifier":"doc:\/\/com.aheaditec.widgetizing.TransactionProcessor\/documentation\/TransactionProcessorFramework\/GetProcessorDataObject","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"GetProcessorDataObject","kind":"identifier"}],"title":"GetProcessorDataObject","navigatorTitle":[{"kind":"identifier","text":"GetProcessorDataObject"}],"kind":"symbol"},"doc://com.aheaditec.widgetizing.TransactionProcessor/documentation/TransactionProcessorFramework/TransactionProcessorState":{"kind":"symbol","url":"\/documentation\/transactionprocessorframework\/transactionprocessorstate","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TransactionProcessorState"}],"title":"TransactionProcessorState","abstract":[{"type":"text","text":"Structure used for persisting TransactionProcessor state"},{"text":" ","type":"text"},{"type":"text","text":"Used as an input parameter to constructor"}],"identifier":"doc:\/\/com.aheaditec.widgetizing.TransactionProcessor\/documentation\/TransactionProcessorFramework\/TransactionProcessorState","role":"symbol","navigatorTitle":[{"text":"TransactionProcessorState","kind":"identifier"}]},"doc://com.aheaditec.widgetizing.TransactionProcessor/documentation/TransactionProcessorFramework/Expiration":{"kind":"symbol","identifier":"doc:\/\/com.aheaditec.widgetizing.TransactionProcessor\/documentation\/TransactionProcessorFramework\/Expiration","type":"topic","abstract":[],"url":"\/documentation\/transactionprocessorframework\/expiration","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Expiration"}],"title":"Expiration","navigatorTitle":[{"text":"Expiration","kind":"identifier"}]},"doc://com.aheaditec.widgetizing.TransactionProcessor/documentation/TransactionProcessorFramework":{"type":"topic","title":"TransactionProcessorFramework","abstract":[],"role":"collection","identifier":"doc:\/\/com.aheaditec.widgetizing.TransactionProcessor\/documentation\/TransactionProcessorFramework","kind":"symbol","url":"\/documentation\/transactionprocessorframework"},"doc://com.aheaditec.widgetizing.TransactionProcessor/documentation/TransactionProcessorFramework/TransactionProcessorClient":{"identifier":"doc:\/\/com.aheaditec.widgetizing.TransactionProcessor\/documentation\/TransactionProcessorFramework\/TransactionProcessorClient","url":"\/documentation\/transactionprocessorframework\/transactionprocessorclient","abstract":[{"text":"Entity providing Transaction Processor services.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TransactionProcessorClient"}],"role":"symbol","kind":"symbol","type":"topic","title":"TransactionProcessorClient","navigatorTitle":[{"text":"TransactionProcessorClient","kind":"identifier"}]},"doc://com.aheaditec.widgetizing.TransactionProcessor/documentation/TransactionProcessorFramework/SetLocaleDataObject":{"identifier":"doc:\/\/com.aheaditec.widgetizing.TransactionProcessor\/documentation\/TransactionProcessorFramework\/SetLocaleDataObject","kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SetLocaleDataObject","kind":"identifier"}],"navigatorTitle":[{"text":"SetLocaleDataObject","kind":"identifier"}],"type":"topic","title":"SetLocaleDataObject","abstract":[],"url":"\/documentation\/transactionprocessorframework\/setlocaledataobject"},"doc://com.aheaditec.widgetizing.TransactionProcessor/documentation/TransactionProcessorFramework/ProcessorState":{"url":"\/documentation\/transactionprocessorframework\/processorstate","title":"ProcessorState","role":"symbol","identifier":"doc:\/\/com.aheaditec.widgetizing.TransactionProcessor\/documentation\/TransactionProcessorFramework\/ProcessorState","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ProcessorState"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProcessorState"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":[{"identifiers":["doc:\/\/com.aheaditec.widgetizing.TransactionProcessor\/documentation\/TransactionProcessorFramework\/TransactionProcessorVersionNumber","doc:\/\/com.aheaditec.widgetizing.TransactionProcessor\/documentation\/TransactionProcessorFramework\/TransactionProcessorVersionString"],"title":"Variables"}],"op":"replace","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"}]}]}