{"identifier":{"url":"doc:\/\/com.aheaditec.widgetizing.ActivationCode\/documentation\/ActivationCodeFramework","interfaceLanguage":"swift"},"hierarchy":{"paths":[[]]},"topicSections":[{"identifiers":["doc:\/\/com.aheaditec.widgetizing.ActivationCode\/documentation\/ActivationCodeFramework\/ActivationCode","doc:\/\/com.aheaditec.widgetizing.ActivationCode\/documentation\/ActivationCodeFramework\/ActivationCodeVerification"],"title":"Classes"},{"identifiers":["doc:\/\/com.aheaditec.widgetizing.ActivationCode\/documentation\/ActivationCodeFramework\/InitResponseDataObject"],"title":"Structures"},{"title":"Enumerations","identifiers":["doc:\/\/com.aheaditec.widgetizing.ActivationCode\/documentation\/ActivationCodeFramework\/ActivationCodeWidgetError"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/activationcodeframework"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/activationcodeframework"]}],"kind":"symbol","metadata":{"title":"ActivationCodeFramework","externalID":"ActivationCodeFramework","role":"collection","symbolKind":"module","roleHeading":"Framework","modules":[{"name":"ActivationCodeFramework"}]},"sections":[],"references":{"doc://com.aheaditec.widgetizing.ActivationCode/documentation/ActivationCodeFramework/InitResponseDataObject":{"title":"InitResponseDataObject","navigatorTitle":[{"text":"InitResponseDataObject","kind":"identifier"}],"url":"\/documentation\/activationcodeframework\/initresponsedataobject","type":"topic","identifier":"doc:\/\/com.aheaditec.widgetizing.ActivationCode\/documentation\/ActivationCodeFramework\/InitResponseDataObject","abstract":[{"type":"text","text":"Models a successful execution of the request."}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"InitResponseDataObject"}]},"doc://com.aheaditec.widgetizing.ActivationCode/documentation/ActivationCodeFramework/ActivationCodeVersionString":{"url":"\/documentation\/activationcodeframework\/activationcodeversionstring","abstract":[{"type":"text","text":"Project version string for ActivationCode."}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.aheaditec.widgetizing.ActivationCode\/documentation\/ActivationCodeFramework\/ActivationCodeVersionString","fragments":[{"kind":"identifier","text":"ActivationCodeVersionString"}],"title":"ActivationCodeVersionString"},"doc://com.aheaditec.widgetizing.ActivationCode/documentation/ActivationCodeFramework/ActivationCode":{"title":"ActivationCode","identifier":"doc:\/\/com.aheaditec.widgetizing.ActivationCode\/documentation\/ActivationCodeFramework\/ActivationCode","kind":"symbol","role":"symbol","url":"\/documentation\/activationcodeframework\/activationcode","abstract":[{"type":"text","text":"Class responsible for Activation Code widget initialization."}],"navigatorTitle":[{"kind":"identifier","text":"ActivationCode"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActivationCode"}]},"doc://com.aheaditec.widgetizing.ActivationCode/documentation/ActivationCodeFramework":{"abstract":[],"identifier":"doc:\/\/com.aheaditec.widgetizing.ActivationCode\/documentation\/ActivationCodeFramework","type":"topic","url":"\/documentation\/activationcodeframework","kind":"symbol","title":"ActivationCodeFramework","role":"collection"},"doc://com.aheaditec.widgetizing.ActivationCode/documentation/ActivationCodeFramework/ActivationCodeWidgetError":{"identifier":"doc:\/\/com.aheaditec.widgetizing.ActivationCode\/documentation\/ActivationCodeFramework\/ActivationCodeWidgetError","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"ActivationCodeWidgetError","kind":"identifier"}],"title":"ActivationCodeWidgetError","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActivationCodeWidgetError"}],"url":"\/documentation\/activationcodeframework\/activationcodewidgeterror","abstract":[{"type":"text","text":"Represents an enum hierarchy for errors related to the widget."}]},"doc://com.aheaditec.widgetizing.ActivationCode/documentation/ActivationCodeFramework/ActivationCodeVersionNumber":{"url":"\/documentation\/activationcodeframework\/activationcodeversionnumber","title":"ActivationCodeVersionNumber","kind":"symbol","identifier":"doc:\/\/com.aheaditec.widgetizing.ActivationCode\/documentation\/ActivationCodeFramework\/ActivationCodeVersionNumber","abstract":[{"text":"Project version number for ActivationCode.","type":"text"}],"role":"symbol","type":"topic","fragments":[{"text":"ActivationCodeVersionNumber","kind":"identifier"}]},"doc://com.aheaditec.widgetizing.ActivationCode/documentation/ActivationCodeFramework/ActivationCodeVerification":{"kind":"symbol","identifier":"doc:\/\/com.aheaditec.widgetizing.ActivationCode\/documentation\/ActivationCodeFramework\/ActivationCodeVerification","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ActivationCodeVerification"}],"title":"ActivationCodeVerification","url":"\/documentation\/activationcodeframework\/activationcodeverification","type":"topic","role":"symbol","abstract":[{"type":"text","text":"A class responsible for Activation Code verification."}],"navigatorTitle":[{"kind":"identifier","text":"ActivationCodeVerification"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":[{"title":"Variables","identifiers":["doc:\/\/com.aheaditec.widgetizing.ActivationCode\/documentation\/ActivationCodeFramework\/ActivationCodeVersionNumber","doc:\/\/com.aheaditec.widgetizing.ActivationCode\/documentation\/ActivationCodeFramework\/ActivationCodeVersionString"]}],"op":"replace","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"}]}]}