{"primaryContentSections":[{"kind":"content","content":[{"level":2,"type":"heading","text":"Overview","anchor":"Overview"}]}],"hierarchy":{"paths":[[]]},"kind":"symbol","sections":[],"topicSections":[{"identifiers":["doc:\/\/com.aheaditec.widgetizing.IAMAttributeFramework\/documentation\/IAMAttributeFramework\/IAMAttribute","doc:\/\/com.aheaditec.widgetizing.IAMAttributeFramework\/documentation\/IAMAttributeFramework\/IAMAttributeVerification"],"title":"Classes"},{"identifiers":["doc:\/\/com.aheaditec.widgetizing.IAMAttributeFramework\/documentation\/IAMAttributeFramework\/InitResponseDataObject"],"title":"Structures"},{"title":"Enumerations","identifiers":["doc:\/\/com.aheaditec.widgetizing.IAMAttributeFramework\/documentation\/IAMAttributeFramework\/IAMAttributeWidgetError"]}],"metadata":{"modules":[{"name":"IAMAttributeFramework"}],"title":"IAMAttributeFramework","symbolKind":"module","role":"collection","roleHeading":"Framework","externalID":"IAMAttributeFramework"},"variants":[{"paths":["\/documentation\/iamattributeframework"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/iamattributeframework"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.aheaditec.widgetizing.IAMAttributeFramework\/documentation\/IAMAttributeFramework","interfaceLanguage":"swift"},"references":{"doc://com.aheaditec.widgetizing.IAMAttributeFramework/documentation/IAMAttributeFramework/InitResponseDataObject":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Models a successful execution of the request."}],"identifier":"doc:\/\/com.aheaditec.widgetizing.IAMAttributeFramework\/documentation\/IAMAttributeFramework\/InitResponseDataObject","kind":"symbol","navigatorTitle":[{"text":"InitResponseDataObject","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"InitResponseDataObject"}],"title":"InitResponseDataObject","url":"\/documentation\/iamattributeframework\/initresponsedataobject"},"doc://com.aheaditec.widgetizing.IAMAttributeFramework/documentation/IAMAttributeFramework/IAMAttribute":{"title":"IAMAttribute","navigatorTitle":[{"kind":"identifier","text":"IAMAttribute"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IAMAttribute"}],"kind":"symbol","url":"\/documentation\/iamattributeframework\/iamattribute","type":"topic","role":"symbol","identifier":"doc:\/\/com.aheaditec.widgetizing.IAMAttributeFramework\/documentation\/IAMAttributeFramework\/IAMAttribute","abstract":[{"type":"text","text":"Class responsible for IAMAttribute widget initialization."}]},"doc://com.aheaditec.widgetizing.IAMAttributeFramework/documentation/IAMAttributeFramework/IAMAttributeFrameworkVersionNumber":{"identifier":"doc:\/\/com.aheaditec.widgetizing.IAMAttributeFramework\/documentation\/IAMAttributeFramework\/IAMAttributeFrameworkVersionNumber","fragments":[{"text":"IAMAttributeFrameworkVersionNumber","kind":"identifier"}],"type":"topic","title":"IAMAttributeFrameworkVersionNumber","role":"symbol","abstract":[{"type":"text","text":"Project version number for IAMAttributeFramework."}],"kind":"symbol","url":"\/documentation\/iamattributeframework\/iamattributeframeworkversionnumber"},"doc://com.aheaditec.widgetizing.IAMAttributeFramework/documentation/IAMAttributeFramework":{"url":"\/documentation\/iamattributeframework","identifier":"doc:\/\/com.aheaditec.widgetizing.IAMAttributeFramework\/documentation\/IAMAttributeFramework","role":"collection","title":"IAMAttributeFramework","kind":"symbol","type":"topic","abstract":[]},"doc://com.aheaditec.widgetizing.IAMAttributeFramework/documentation/IAMAttributeFramework/IAMAttributeVerification":{"navigatorTitle":[{"kind":"identifier","text":"IAMAttributeVerification"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IAMAttributeVerification","kind":"identifier"}],"url":"\/documentation\/iamattributeframework\/iamattributeverification","role":"symbol","identifier":"doc:\/\/com.aheaditec.widgetizing.IAMAttributeFramework\/documentation\/IAMAttributeFramework\/IAMAttributeVerification","kind":"symbol","abstract":[{"text":"A class responsible forIAMAttribute verification.","type":"text"}],"title":"IAMAttributeVerification"},"doc://com.aheaditec.widgetizing.IAMAttributeFramework/documentation/IAMAttributeFramework/IAMAttributeWidgetError":{"title":"IAMAttributeWidgetError","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"IAMAttributeWidgetError","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"IAMAttributeWidgetError"}],"url":"\/documentation\/iamattributeframework\/iamattributewidgeterror","type":"topic","abstract":[{"type":"text","text":"Represents an enum hierarchy for errors related to the widget."}],"identifier":"doc:\/\/com.aheaditec.widgetizing.IAMAttributeFramework\/documentation\/IAMAttributeFramework\/IAMAttributeWidgetError","role":"symbol"},"doc://com.aheaditec.widgetizing.IAMAttributeFramework/documentation/IAMAttributeFramework/IAMAttributeFrameworkVersionString":{"kind":"symbol","title":"IAMAttributeFrameworkVersionString","fragments":[{"kind":"identifier","text":"IAMAttributeFrameworkVersionString"}],"identifier":"doc:\/\/com.aheaditec.widgetizing.IAMAttributeFramework\/documentation\/IAMAttributeFramework\/IAMAttributeFrameworkVersionString","role":"symbol","abstract":[{"text":"Project version string for IAMAttributeFramework.","type":"text"}],"url":"\/documentation\/iamattributeframework\/iamattributeframeworkversionstring","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.aheaditec.widgetizing.IAMAttributeFramework\/documentation\/IAMAttributeFramework\/IAMAttributeFrameworkVersionNumber","doc:\/\/com.aheaditec.widgetizing.IAMAttributeFramework\/documentation\/IAMAttributeFramework\/IAMAttributeFrameworkVersionString"],"title":"Variables"}]},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"}],"traits":[{"interfaceLanguage":"occ"}]}]}