{"hierarchy":{"paths":[[]]},"sections":[],"identifier":{"url":"doc:\/\/com.aheaditec.widgetizing.Nickname\/documentation\/NicknameFramework","interfaceLanguage":"swift"},"metadata":{"externalID":"NicknameFramework","role":"collection","modules":[{"name":"NicknameFramework"}],"roleHeading":"Framework","symbolKind":"module","title":"NicknameFramework"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","topicSections":[{"title":"Classes","identifiers":["doc:\/\/com.aheaditec.widgetizing.Nickname\/documentation\/NicknameFramework\/Nickname","doc:\/\/com.aheaditec.widgetizing.Nickname\/documentation\/NicknameFramework\/NicknameFormat","doc:\/\/com.aheaditec.widgetizing.Nickname\/documentation\/NicknameFramework\/NicknameValidation","doc:\/\/com.aheaditec.widgetizing.Nickname\/documentation\/NicknameFramework\/NicknameValidationResult"]},{"identifiers":["doc:\/\/com.aheaditec.widgetizing.Nickname\/documentation\/NicknameFramework\/InitResponseDataObject","doc:\/\/com.aheaditec.widgetizing.Nickname\/documentation\/NicknameFramework\/NicknameDeterminant","doc:\/\/com.aheaditec.widgetizing.Nickname\/documentation\/NicknameFramework\/NicknameValidationError","doc:\/\/com.aheaditec.widgetizing.Nickname\/documentation\/NicknameFramework\/NicknameVerification"],"title":"Structures"},{"identifiers":["doc:\/\/com.aheaditec.widgetizing.Nickname\/documentation\/NicknameFramework\/NicknameWidgetError"],"title":"Enumerations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nicknameframework"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nicknameframework"]}],"references":{"doc://com.aheaditec.widgetizing.Nickname/documentation/NicknameFramework/InitResponseDataObject":{"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"InitResponseDataObject","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/nicknameframework\/initresponsedataobject","navigatorTitle":[{"kind":"identifier","text":"InitResponseDataObject"}],"identifier":"doc:\/\/com.aheaditec.widgetizing.Nickname\/documentation\/NicknameFramework\/InitResponseDataObject","abstract":[{"type":"text","text":"Deserialized backend response containing a list of "},{"code":"NicknameFormat","type":"codeVoice"},{"type":"text","text":" and "},{"type":"codeVoice","code":"NicknameDeterminant"},{"type":"text","text":"."}],"title":"InitResponseDataObject"},"doc://com.aheaditec.widgetizing.Nickname/documentation/NicknameFramework/NicknameValidationError":{"url":"\/documentation\/nicknameframework\/nicknamevalidationerror","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"NicknameValidationError","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"NicknameValidationError"}],"title":"NicknameValidationError","kind":"symbol","abstract":[{"type":"text","text":"Represents an error that occurs when a nickname validation against a specific muc fails."}],"role":"symbol","identifier":"doc:\/\/com.aheaditec.widgetizing.Nickname\/documentation\/NicknameFramework\/NicknameValidationError"},"doc://com.aheaditec.widgetizing.Nickname/documentation/NicknameFramework/Nickname":{"title":"Nickname","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Nickname"}],"identifier":"doc:\/\/com.aheaditec.widgetizing.Nickname\/documentation\/NicknameFramework\/Nickname","navigatorTitle":[{"text":"Nickname","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Initial class in NicknameWidget call sequence"}],"url":"\/documentation\/nicknameframework\/nickname","kind":"symbol"},"doc://com.aheaditec.widgetizing.Nickname/documentation/NicknameFramework/NicknameDeterminant":{"title":"NicknameDeterminant","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"NicknameDeterminant","kind":"identifier"}],"identifier":"doc:\/\/com.aheaditec.widgetizing.Nickname\/documentation\/NicknameFramework\/NicknameDeterminant","navigatorTitle":[{"kind":"identifier","text":"NicknameDeterminant"}],"type":"topic","abstract":[{"type":"text","text":"Describes MUC guessing rules for an invalid nickname input. Note that there can be multiple occurrences of the same muc within this array."}],"url":"\/documentation\/nicknameframework\/nicknamedeterminant","kind":"symbol"},"doc://com.aheaditec.widgetizing.Nickname/documentation/NicknameFramework":{"title":"NicknameFramework","type":"topic","kind":"symbol","url":"\/documentation\/nicknameframework","identifier":"doc:\/\/com.aheaditec.widgetizing.Nickname\/documentation\/NicknameFramework","role":"collection","abstract":[]},"doc://com.aheaditec.widgetizing.Nickname/documentation/NicknameFramework/NicknameFormat":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NicknameFormat"}],"type":"topic","title":"NicknameFormat","url":"\/documentation\/nicknameframework\/nicknameformat","kind":"symbol","abstract":[{"type":"text","text":"Represents the format and validation rules for a nickname in a specific context."}],"identifier":"doc:\/\/com.aheaditec.widgetizing.Nickname\/documentation\/NicknameFramework\/NicknameFormat","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NicknameFormat"}]},"doc://com.aheaditec.widgetizing.Nickname/documentation/NicknameFramework/NicknameValidationResult":{"identifier":"doc:\/\/com.aheaditec.widgetizing.Nickname\/documentation\/NicknameFramework\/NicknameValidationResult","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NicknameValidationResult","kind":"identifier"}],"title":"NicknameValidationResult","url":"\/documentation\/nicknameframework\/nicknamevalidationresult","navigatorTitle":[{"text":"NicknameValidationResult","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Represents the result of a nickname validation against a specific NicknameFormat."}],"role":"symbol"},"doc://com.aheaditec.widgetizing.Nickname/documentation/NicknameFramework/NicknameVerification":{"navigatorTitle":[{"kind":"identifier","text":"NicknameVerification"}],"title":"NicknameVerification","type":"topic","kind":"symbol","url":"\/documentation\/nicknameframework\/nicknameverification","identifier":"doc:\/\/com.aheaditec.widgetizing.Nickname\/documentation\/NicknameFramework\/NicknameVerification","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"NicknameVerification","kind":"identifier"}],"abstract":[{"text":"Represents a class for verifying or cancelling nickname widget flow.","type":"text"}]},"doc://com.aheaditec.widgetizing.Nickname/documentation/NicknameFramework/NicknameWidgetError":{"navigatorTitle":[{"kind":"identifier","text":"NicknameWidgetError"}],"kind":"symbol","identifier":"doc:\/\/com.aheaditec.widgetizing.Nickname\/documentation\/NicknameFramework\/NicknameWidgetError","abstract":[{"type":"text","text":"Represents an enum hierarchy for errors related to the Nickname widget."}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NicknameWidgetError"}],"type":"topic","title":"NicknameWidgetError","url":"\/documentation\/nicknameframework\/nicknamewidgeterror"},"doc://com.aheaditec.widgetizing.Nickname/documentation/NicknameFramework/NicknameValidation":{"title":"NicknameValidation","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NicknameValidation"}],"identifier":"doc:\/\/com.aheaditec.widgetizing.Nickname\/documentation\/NicknameFramework\/NicknameValidation","navigatorTitle":[{"text":"NicknameValidation","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Represents a class for validating nicknames using provided rules from an "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.aheaditec.widgetizing.Nickname\/documentation\/NicknameFramework\/InitResponseDataObject"},{"text":".","type":"text"}],"url":"\/documentation\/nicknameframework\/nicknamevalidation","kind":"symbol"},"doc://com.aheaditec.widgetizing.Nickname/documentation/NicknameFramework/NicknameVersionNumber":{"title":"NicknameVersionNumber","role":"symbol","fragments":[{"kind":"identifier","text":"NicknameVersionNumber"}],"identifier":"doc:\/\/com.aheaditec.widgetizing.Nickname\/documentation\/NicknameFramework\/NicknameVersionNumber","type":"topic","abstract":[{"text":"Project version number for Nickname.","type":"text"}],"url":"\/documentation\/nicknameframework\/nicknameversionnumber","kind":"symbol"},"doc://com.aheaditec.widgetizing.Nickname/documentation/NicknameFramework/NicknameVersionString":{"title":"NicknameVersionString","type":"topic","fragments":[{"kind":"identifier","text":"NicknameVersionString"}],"abstract":[{"text":"Project version string for Nickname.","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.aheaditec.widgetizing.Nickname\/documentation\/NicknameFramework\/NicknameVersionString","url":"\/documentation\/nicknameframework\/nicknameversionstring"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[{"identifiers":["doc:\/\/com.aheaditec.widgetizing.Nickname\/documentation\/NicknameFramework\/NicknameVersionNumber","doc:\/\/com.aheaditec.widgetizing.Nickname\/documentation\/NicknameFramework\/NicknameVersionString"],"title":"Variables"}],"op":"replace","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"}]}]}