{"topicSections":[{"title":"Classes","identifiers":["doc:\/\/com.aheaditec.widgetizing.EmailCheckFramework\/documentation\/EmailCheckFramework\/EmailCheck","doc:\/\/com.aheaditec.widgetizing.EmailCheckFramework\/documentation\/EmailCheckFramework\/EmailCheckPolling","doc:\/\/com.aheaditec.widgetizing.EmailCheckFramework\/documentation\/EmailCheckFramework\/EmailCheckVerification"]},{"title":"Structures","identifiers":["doc:\/\/com.aheaditec.widgetizing.EmailCheckFramework\/documentation\/EmailCheckFramework\/EmailFormat","doc:\/\/com.aheaditec.widgetizing.EmailCheckFramework\/documentation\/EmailCheckFramework\/WidgetState"]},{"title":"Enumerations","identifiers":["doc:\/\/com.aheaditec.widgetizing.EmailCheckFramework\/documentation\/EmailCheckFramework\/EmailCheckWidgetError","doc:\/\/com.aheaditec.widgetizing.EmailCheckFramework\/documentation\/EmailCheckFramework\/InitializeState","doc:\/\/com.aheaditec.widgetizing.EmailCheckFramework\/documentation\/EmailCheckFramework\/PollState","doc:\/\/com.aheaditec.widgetizing.EmailCheckFramework\/documentation\/EmailCheckFramework\/VerifyState"]}],"sections":[],"primaryContentSections":[{"kind":"content","content":[{"text":"Overview","level":2,"anchor":"Overview","type":"heading"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/emailcheckframework"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/emailcheckframework"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[[]]},"kind":"symbol","metadata":{"title":"EmailCheckFramework","externalID":"EmailCheckFramework","role":"collection","symbolKind":"module","modules":[{"name":"EmailCheckFramework"}],"roleHeading":"Framework"},"identifier":{"url":"doc:\/\/com.aheaditec.widgetizing.EmailCheckFramework\/documentation\/EmailCheckFramework","interfaceLanguage":"swift"},"references":{"doc://com.aheaditec.widgetizing.EmailCheckFramework/documentation/EmailCheckFramework/EmailCheckFrameworkVersionString":{"type":"topic","identifier":"doc:\/\/com.aheaditec.widgetizing.EmailCheckFramework\/documentation\/EmailCheckFramework\/EmailCheckFrameworkVersionString","title":"EmailCheckFrameworkVersionString","abstract":[{"text":"Project version string for EmailCheckFramework.","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/emailcheckframework\/emailcheckframeworkversionstring","fragments":[{"kind":"identifier","text":"EmailCheckFrameworkVersionString"}]},"doc://com.aheaditec.widgetizing.EmailCheckFramework/documentation/EmailCheckFramework/VerifyState":{"kind":"symbol","title":"VerifyState","navigatorTitle":[{"kind":"identifier","text":"VerifyState"}],"identifier":"doc:\/\/com.aheaditec.widgetizing.EmailCheckFramework\/documentation\/EmailCheckFramework\/VerifyState","url":"\/documentation\/emailcheckframework\/verifystate","type":"topic","abstract":[{"type":"text","text":"Represents an enum containing state after called verify."}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"VerifyState"}],"role":"symbol"},"doc://com.aheaditec.widgetizing.EmailCheckFramework/documentation/EmailCheckFramework":{"role":"collection","title":"EmailCheckFramework","abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.aheaditec.widgetizing.EmailCheckFramework\/documentation\/EmailCheckFramework","url":"\/documentation\/emailcheckframework"},"doc://com.aheaditec.widgetizing.EmailCheckFramework/documentation/EmailCheckFramework/EmailCheck":{"role":"symbol","url":"\/documentation\/emailcheckframework\/emailcheck","title":"EmailCheck","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EmailCheck","kind":"identifier"}],"abstract":[{"text":"Class responsible for EmailCheck widget initialization.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.aheaditec.widgetizing.EmailCheckFramework\/documentation\/EmailCheckFramework\/EmailCheck","navigatorTitle":[{"text":"EmailCheck","kind":"identifier"}]},"doc://com.aheaditec.widgetizing.EmailCheckFramework/documentation/EmailCheckFramework/EmailCheckVerification":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"EmailCheckVerification"}],"abstract":[{"type":"text","text":"A class responsible for EmailCheck verification."}],"role":"symbol","url":"\/documentation\/emailcheckframework\/emailcheckverification","title":"EmailCheckVerification","identifier":"doc:\/\/com.aheaditec.widgetizing.EmailCheckFramework\/documentation\/EmailCheckFramework\/EmailCheckVerification","kind":"symbol","navigatorTitle":[{"text":"EmailCheckVerification","kind":"identifier"}]},"doc://com.aheaditec.widgetizing.EmailCheckFramework/documentation/EmailCheckFramework/InitializeState":{"kind":"symbol","type":"topic","title":"InitializeState","role":"symbol","url":"\/documentation\/emailcheckframework\/initializestate","navigatorTitle":[{"kind":"identifier","text":"InitializeState"}],"identifier":"doc:\/\/com.aheaditec.widgetizing.EmailCheckFramework\/documentation\/EmailCheckFramework\/InitializeState","abstract":[{"text":"Represents an enum containing state after called initialize.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"InitializeState"}]},"doc://com.aheaditec.widgetizing.EmailCheckFramework/documentation/EmailCheckFramework/EmailFormat":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"EmailFormat"}],"title":"EmailFormat","type":"topic","kind":"symbol","identifier":"doc:\/\/com.aheaditec.widgetizing.EmailCheckFramework\/documentation\/EmailCheckFramework\/EmailFormat","url":"\/documentation\/emailcheckframework\/emailformat","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EmailFormat","kind":"identifier"}]},"doc://com.aheaditec.widgetizing.EmailCheckFramework/documentation/EmailCheckFramework/EmailCheckPolling":{"kind":"symbol","title":"EmailCheckPolling","navigatorTitle":[{"kind":"identifier","text":"EmailCheckPolling"}],"identifier":"doc:\/\/com.aheaditec.widgetizing.EmailCheckFramework\/documentation\/EmailCheckFramework\/EmailCheckPolling","url":"\/documentation\/emailcheckframework\/emailcheckpolling","type":"topic","abstract":[{"text":"A class responsible for EmailCheck polling.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EmailCheckPolling"}],"role":"symbol"},"doc://com.aheaditec.widgetizing.EmailCheckFramework/documentation/EmailCheckFramework/WidgetState":{"identifier":"doc:\/\/com.aheaditec.widgetizing.EmailCheckFramework\/documentation\/EmailCheckFramework\/WidgetState","type":"topic","url":"\/documentation\/emailcheckframework\/widgetstate","navigatorTitle":[{"text":"WidgetState","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"WidgetState"}],"abstract":[{"text":"Current state of the widget, can be used to initialize ","type":"text"},{"identifier":"doc:\/\/com.aheaditec.widgetizing.EmailCheckFramework\/documentation\/EmailCheckFramework\/EmailCheckPolling","isActive":true,"type":"reference"},{"text":" class.","type":"text"}],"title":"WidgetState"},"doc://com.aheaditec.widgetizing.EmailCheckFramework/documentation/EmailCheckFramework/EmailCheckWidgetError":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"EmailCheckWidgetError"}],"abstract":[{"type":"text","text":"Represents an enum hierarchy for errors related to the widget."}],"navigatorTitle":[{"kind":"identifier","text":"EmailCheckWidgetError"}],"type":"topic","title":"EmailCheckWidgetError","url":"\/documentation\/emailcheckframework\/emailcheckwidgeterror","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.aheaditec.widgetizing.EmailCheckFramework\/documentation\/EmailCheckFramework\/EmailCheckWidgetError"},"doc://com.aheaditec.widgetizing.EmailCheckFramework/documentation/EmailCheckFramework/PollState":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PollState"}],"title":"PollState","type":"topic","abstract":[{"type":"text","text":"Represents an enum containing state after called poll."}],"kind":"symbol","navigatorTitle":[{"text":"PollState","kind":"identifier"}],"url":"\/documentation\/emailcheckframework\/pollstate","role":"symbol","identifier":"doc:\/\/com.aheaditec.widgetizing.EmailCheckFramework\/documentation\/EmailCheckFramework\/PollState"},"doc://com.aheaditec.widgetizing.EmailCheckFramework/documentation/EmailCheckFramework/EmailCheckFrameworkVersionNumber":{"role":"symbol","identifier":"doc:\/\/com.aheaditec.widgetizing.EmailCheckFramework\/documentation\/EmailCheckFramework\/EmailCheckFrameworkVersionNumber","abstract":[{"type":"text","text":"Project version number for EmailCheckFramework."}],"type":"topic","title":"EmailCheckFrameworkVersionNumber","fragments":[{"kind":"identifier","text":"EmailCheckFrameworkVersionNumber"}],"kind":"symbol","url":"\/documentation\/emailcheckframework\/emailcheckframeworkversionnumber"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":[{"identifiers":["doc:\/\/com.aheaditec.widgetizing.EmailCheckFramework\/documentation\/EmailCheckFramework\/EmailCheckFrameworkVersionNumber","doc:\/\/com.aheaditec.widgetizing.EmailCheckFramework\/documentation\/EmailCheckFramework\/EmailCheckFrameworkVersionString"],"title":"Variables"}],"op":"replace","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"}]}]}